using InventoryWarehouseApi.Application.Common;using InventoryWarehouseApi.Application.LowStock;using InventoryWarehouseApi.Domain.Entities;using Microsoft.EntityFrameworkCore;
namespace InventoryWarehouseApi.Infrastructure.Persistence;
internal sealed class LowStockRepository(InventoryWarehouseDbContext db):ILowStockRepository
{
 public async Task<LowStockThresholdResponse> UpsertThresholdAsync(Guid p,Guid w,Guid l,UpsertLowStockThresholdRequest r,DateTimeOffset now,CancellationToken ct){if(!await db.Products.AnyAsync(x=>x.Id==p,ct))throw new NotFoundException("Product was not found.");if(!await db.Warehouses.AnyAsync(x=>x.Id==w,ct))throw new NotFoundException("Warehouse was not found.");if(!await db.WarehouseLocations.AnyAsync(x=>x.WarehouseId==w&&x.Id==l,ct))throw new NotFoundException("Warehouse location was not found.");var x=await db.LowStockThresholds.SingleOrDefaultAsync(x=>x.ProductId==p&&x.WarehouseId==w&&x.WarehouseLocationId==l,ct);if(x is null){x=new(Guid.NewGuid(),p,w,l,r.ThresholdQuantity,r.IsEnabled,now);db.Add(x);}else x.Update(r.ThresholdQuantity,r.IsEnabled,now);await db.SaveChangesAsync(ct);return Map(x);}
 public async Task<LowStockThresholdResponse?> GetThresholdAsync(Guid p,Guid w,Guid l,CancellationToken ct){var x=await db.LowStockThresholds.AsNoTracking().SingleOrDefaultAsync(x=>x.ProductId==p&&x.WarehouseId==w&&x.WarehouseLocationId==l,ct);return x is null?null:Map(x);}
 public async Task<PagedResult<LowStockThresholdResponse>> ListThresholdsAsync(LowStockThresholdQuery q,CancellationToken ct){var z=db.LowStockThresholds.AsNoTracking();if(q.ProductId.HasValue)z=z.Where(x=>x.ProductId==q.ProductId);if(q.WarehouseId.HasValue)z=z.Where(x=>x.WarehouseId==q.WarehouseId);if(q.IsEnabled.HasValue)z=z.Where(x=>x.IsEnabled==q.IsEnabled);int n=await z.CountAsync(ct);var items=await z.OrderBy(x=>x.ProductId).ThenBy(x=>x.WarehouseId).ThenBy(x=>x.WarehouseLocationId).Skip((q.PageNumber-1)*q.PageSize).Take(q.PageSize).ToListAsync(ct);return new(items.Select(Map).ToList(),q.PageNumber,q.PageSize,n);}
 private IQueryable<LowStockResponse> LowQuery()=>from t in db.LowStockThresholds.AsNoTracking() join p in db.Products on t.ProductId equals p.Id join w in db.Warehouses on t.WarehouseId equals w.Id join l in db.WarehouseLocations on new{t.WarehouseId,Id=t.WarehouseLocationId} equals new{l.WarehouseId,l.Id} join b in db.InventoryBalances on new{t.ProductId,t.WarehouseId,t.WarehouseLocationId} equals new{b.ProductId,b.WarehouseId,b.WarehouseLocationId} into bs from b in bs.DefaultIfEmpty() let onHand=b==null?0:b.OnHandQuantity let reserved=b==null?0:b.ReservedQuantity let available=onHand-reserved where t.IsEnabled&&p.IsActive&&w.IsActive&&l.IsActive&&available<=t.ThresholdQuantity select new LowStockResponse(t.Id,p.Id,p.Sku,p.Name,w.Id,w.Code,w.Name,l.Id,l.Code,l.Name,t.ThresholdQuantity,onHand,reserved,available,t.ThresholdQuantity-available>0?t.ThresholdQuantity-available:0);
 public async Task<PagedResult<LowStockResponse>> ListLowStockAsync(LowStockQuery q,CancellationToken ct)
 {
  var z=from t in db.LowStockThresholds.AsNoTracking() join p in db.Products on t.ProductId equals p.Id join w in db.Warehouses on t.WarehouseId equals w.Id join l in db.WarehouseLocations on new{t.WarehouseId,Id=t.WarehouseLocationId} equals new{l.WarehouseId,l.Id} join b in db.InventoryBalances on new{t.ProductId,t.WarehouseId,t.WarehouseLocationId} equals new{b.ProductId,b.WarehouseId,b.WarehouseLocationId} into bs from b in bs.DefaultIfEmpty() let onHand=b==null?0:b.OnHandQuantity let reserved=b==null?0:b.ReservedQuantity let available=onHand-reserved where t.IsEnabled&&p.IsActive&&w.IsActive&&l.IsActive&&available<=t.ThresholdQuantity select new{t,p,w,l,onHand,reserved,available};
  if(q.ProductId.HasValue)z=z.Where(x=>x.p.Id==q.ProductId);if(q.WarehouseId.HasValue)z=z.Where(x=>x.w.Id==q.WarehouseId);int n=await z.CountAsync(ct);
  z=db.Database.ProviderName=="Microsoft.EntityFrameworkCore.Sqlite"?z.OrderBy(x=>x.p.Id).ThenBy(x=>x.w.Id).ThenBy(x=>x.l.Id):z.OrderBy(x=>x.available).ThenBy(x=>x.p.Id).ThenBy(x=>x.w.Id).ThenBy(x=>x.l.Id);
  var items=await z.Skip((q.PageNumber-1)*q.PageSize).Take(q.PageSize).Select(x=>new LowStockResponse(x.t.Id,x.p.Id,x.p.Sku,x.p.Name,x.w.Id,x.w.Code,x.w.Name,x.l.Id,x.l.Code,x.l.Name,x.t.ThresholdQuantity,x.onHand,x.reserved,x.available,x.t.ThresholdQuantity-x.available>0?x.t.ThresholdQuantity-x.available:0)).ToListAsync(ct);
  return new(items,q.PageNumber,q.PageSize,n);
 }
 public async Task<PagedResult<LowStockAlertResponse>> ListAlertsAsync(LowStockAlertQuery q,CancellationToken ct)
 {
  var z=from a in db.LowStockAlerts.AsNoTracking() join t in db.LowStockThresholds on a.LowStockThresholdId equals t.Id join p in db.Products on t.ProductId equals p.Id join w in db.Warehouses on t.WarehouseId equals w.Id join l in db.WarehouseLocations on new{t.WarehouseId,Id=t.WarehouseLocationId} equals new{l.WarehouseId,l.Id} select new{Alert=a,Threshold=t,Product=p,Warehouse=w,Location=l};
  if(q.IsActive==true)z=z.Where(x=>x.Alert.ResolvedAtUtc==null);else if(q.IsActive==false)z=z.Where(x=>x.Alert.ResolvedAtUtc!=null);
  if(q.ProductId.HasValue)z=z.Where(x=>x.Threshold.ProductId==q.ProductId);if(q.WarehouseId.HasValue)z=z.Where(x=>x.Threshold.WarehouseId==q.WarehouseId);
  int n=await z.CountAsync(ct);
  if(db.Database.ProviderName=="Microsoft.EntityFrameworkCore.Sqlite")
  {
   int offset=(q.PageNumber-1)*q.PageSize, noActiveFilter=q.IsActive.HasValue?0:1, active=q.IsActive==true?1:0, resolved=q.IsActive==false?1:0, noProductFilter=q.ProductId.HasValue?0:1, noWarehouseFilter=q.WarehouseId.HasValue?0:1;
   List<LowStockAlert> page=await db.LowStockAlerts.FromSqlInterpolated($$"""
    SELECT a.* FROM LowStockAlerts AS a
    INNER JOIN LowStockThresholds AS t ON a.LowStockThresholdId = t.Id
    WHERE ({{noActiveFilter}} = 1 OR ({{active}} = 1 AND a.ResolvedAtUtc IS NULL) OR ({{resolved}} = 1 AND a.ResolvedAtUtc IS NOT NULL))
      AND ({{noProductFilter}} = 1 OR t.ProductId = {{q.ProductId}})
      AND ({{noWarehouseFilter}} = 1 OR t.WarehouseId = {{q.WarehouseId}})
    ORDER BY a.TriggeredAtUtc DESC, a.Id DESC
    LIMIT {{q.PageSize}} OFFSET {{offset}}
    """).AsNoTracking().ToListAsync(ct);
   Guid[] ids=page.Select(x=>x.Id).ToArray();
   List<LowStockAlertResponse> details=await (from a in db.LowStockAlerts.AsNoTracking() join t in db.LowStockThresholds on a.LowStockThresholdId equals t.Id join p in db.Products on t.ProductId equals p.Id join w in db.Warehouses on t.WarehouseId equals w.Id join l in db.WarehouseLocations on new{t.WarehouseId,Id=t.WarehouseLocationId} equals new{l.WarehouseId,l.Id} where ids.Contains(a.Id) select new LowStockAlertResponse(a.Id,a.LowStockThresholdId,p.Id,p.Sku,w.Id,w.Code,l.Id,l.Code,a.ThresholdQuantity,a.AvailableQuantity,a.TriggeredAtUtc,a.LastObservedAtUtc,a.ResolvedAtUtc,a.ResolvedAtUtc==null)).ToListAsync(ct);
   Dictionary<Guid,int> order=ids.Select((id,index)=>new{id,index}).ToDictionary(x=>x.id,x=>x.index);details.Sort((x,y)=>order[x.Id].CompareTo(order[y.Id]));
   return new(details,q.PageNumber,q.PageSize,n);
  }
  var items=await z.OrderByDescending(x=>x.Alert.TriggeredAtUtc).ThenByDescending(x=>x.Alert.Id).Skip((q.PageNumber-1)*q.PageSize).Take(q.PageSize)
   .Select(x=>new LowStockAlertResponse(x.Alert.Id,x.Alert.LowStockThresholdId,x.Product.Id,x.Product.Sku,x.Warehouse.Id,x.Warehouse.Code,x.Location.Id,x.Location.Code,x.Alert.ThresholdQuantity,x.Alert.AvailableQuantity,x.Alert.TriggeredAtUtc,x.Alert.LastObservedAtUtc,x.Alert.ResolvedAtUtc,x.Alert.ResolvedAtUtc==null)).ToListAsync(ct);
  return new(items,q.PageNumber,q.PageSize,n);
 }
 public async Task<LowStockMonitoringRunResult> ReconcileAsync(DateTimeOffset at,CancellationToken ct){var positions=await (from t in db.LowStockThresholds join p in db.Products on t.ProductId equals p.Id join w in db.Warehouses on t.WarehouseId equals w.Id join l in db.WarehouseLocations on new{t.WarehouseId,Id=t.WarehouseLocationId} equals new{l.WarehouseId,l.Id} join b in db.InventoryBalances on new{t.ProductId,t.WarehouseId,t.WarehouseLocationId} equals new{b.ProductId,b.WarehouseId,b.WarehouseLocationId} into bs from b in bs.DefaultIfEmpty() let available=b==null?0:b.OnHandQuantity-b.ReservedQuantity select new{Threshold=t,Available=available,Monitorable=t.IsEnabled&&p.IsActive&&w.IsActive&&l.IsActive}).ToListAsync(ct);var active=await db.LowStockAlerts.Where(x=>x.ResolvedAtUtc==null).ToListAsync(ct);var low=positions.Where(x=>x.Monitorable&&x.Available<=x.Threshold.ThresholdQuantity).ToDictionary(x=>x.Threshold.Id);var availability=positions.ToDictionary(x=>x.Threshold.Id,x=>x.Available);int triggered=0,updated=0,resolved=0;foreach(var x in active){if(low.TryGetValue(x.LowStockThresholdId,out var current)){x.Observe(current.Threshold.ThresholdQuantity,current.Available,at);updated++;low.Remove(x.LowStockThresholdId);}else{x.Resolve(availability.GetValueOrDefault(x.LowStockThresholdId),at);resolved++;}}foreach(var current in low.Values){db.LowStockAlerts.Add(new(Guid.NewGuid(),current.Threshold.Id,current.Threshold.ThresholdQuantity,current.Available,at));triggered++;}await db.SaveChangesAsync(ct);return new(positions.Count(x=>x.Monitorable),positions.Count(x=>x.Monitorable&&x.Available<=x.Threshold.ThresholdQuantity),triggered,updated,resolved);}
 private static LowStockThresholdResponse Map(LowStockThreshold x)=>new(x.Id,x.ProductId,x.WarehouseId,x.WarehouseLocationId,x.ThresholdQuantity,x.IsEnabled,x.CreatedAtUtc,x.UpdatedAtUtc);
}
