using InventoryWarehouseApi.Domain.Enums;

namespace InventoryWarehouseApi.Application.Reporting;

public abstract record ReportPageQuery(int PageNumber = 1, int PageSize = 20, string? SortBy = null, string SortDirection = "asc");
public sealed record InventorySummaryQuery(int PageNumber=1,int PageSize=20,string? Search=null,bool? IsActive=null,string? SortBy="sku",string SortDirection="asc") : ReportPageQuery(PageNumber,PageSize,SortBy,SortDirection);
public sealed record WarehouseInventoryQuery(int PageNumber=1,int PageSize=20,string? Search=null,bool? IsActive=null,string? SortBy="sku",string SortDirection="asc") : ReportPageQuery(PageNumber,PageSize,SortBy,SortDirection);
public sealed record StockMovementReportQuery(int PageNumber=1,int PageSize=20,Guid? ProductId=null,Guid? WarehouseId=null,Guid? WarehouseLocationId=null,StockMovementType? MovementType=null,DateTimeOffset? FromUtc=null,DateTimeOffset? ToUtc=null,string? ReferenceType=null,string? ReferenceId=null,string? SortBy="occurredAt",string SortDirection="desc") : ReportPageQuery(PageNumber,PageSize,SortBy,SortDirection);
public sealed record LowStockReportQuery(int PageNumber=1,int PageSize=20,string? Search=null,Guid? ProductId=null,Guid? WarehouseId=null,string? SortBy="shortage",string SortDirection="desc") : ReportPageQuery(PageNumber,PageSize,SortBy,SortDirection);
public sealed record ProductStockHistoryQuery(int PageNumber=1,int PageSize=20,Guid? WarehouseId=null,Guid? WarehouseLocationId=null,StockMovementType? MovementType=null,DateTimeOffset? FromUtc=null,DateTimeOffset? ToUtc=null,string? SortBy="occurredAt",string SortDirection="desc") : ReportPageQuery(PageNumber,PageSize,SortBy,SortDirection);

public sealed class InventorySummaryItem { public Guid ProductId{get;set;} public string ProductSku{get;set;}=null!;public string ProductName{get;set;}=null!;public bool IsProductActive{get;set;}public decimal OnHandQuantity{get;set;}public decimal ReservedQuantity{get;set;}public decimal AvailableQuantity{get;set;}public int WarehouseCount{get;set;}public int LocationCount{get;set;} }
public sealed class WarehouseInventoryItem { public Guid ProductId{get;set;}public string ProductSku{get;set;}=null!;public string ProductName{get;set;}=null!;public bool IsProductActive{get;set;}public decimal OnHandQuantity{get;set;}public decimal ReservedQuantity{get;set;}public decimal AvailableQuantity{get;set;}public int LocationCount{get;set;} }
public sealed class StockMovementReportItem { public Guid MovementId{get;set;}public DateTimeOffset OccurredAtUtc{get;set;}public StockMovementType MovementType{get;set;}public decimal Quantity{get;set;}public Guid ProductId{get;set;}public string ProductSku{get;set;}=null!;public string ProductName{get;set;}=null!;public Guid WarehouseId{get;set;}public string WarehouseCode{get;set;}=null!;public string WarehouseName{get;set;}=null!;public Guid WarehouseLocationId{get;set;}public string WarehouseLocationCode{get;set;}=null!;public string WarehouseLocationName{get;set;}=null!;public string? ReferenceType{get;set;}public string? ReferenceId{get;set;} }
public sealed class LowStockReportItem { public Guid LowStockThresholdId{get;set;}public Guid ProductId{get;set;}public string ProductSku{get;set;}=null!;public string ProductName{get;set;}=null!;public Guid WarehouseId{get;set;}public string WarehouseCode{get;set;}=null!;public string WarehouseName{get;set;}=null!;public Guid WarehouseLocationId{get;set;}public string WarehouseLocationCode{get;set;}=null!;public string WarehouseLocationName{get;set;}=null!;public decimal ThresholdQuantity{get;set;}public decimal OnHandQuantity{get;set;}public decimal ReservedQuantity{get;set;}public decimal AvailableQuantity{get;set;}public decimal ShortageQuantity{get;set;} }
public sealed class ProductStockHistoryItem { public Guid MovementId{get;set;}public Guid ProductId{get;set;}public string ProductSku{get;set;}=null!;public string ProductName{get;set;}=null!;public DateTimeOffset OccurredAtUtc{get;set;}public StockMovementType MovementType{get;set;}public decimal Quantity{get;set;}public decimal QuantityChange{get;set;}public Guid WarehouseId{get;set;}public string WarehouseCode{get;set;}=null!;public string WarehouseName{get;set;}=null!;public Guid WarehouseLocationId{get;set;}public string WarehouseLocationCode{get;set;}=null!;public string WarehouseLocationName{get;set;}=null!;public string? ReferenceType{get;set;}public string? ReferenceId{get;set;} }
