using InventoryWarehouseApi.Application.Common;using InventoryWarehouseApi.Application.LowStock;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Authorization;using InventoryWarehouseApi.Application.Authentication;
namespace InventoryWarehouseApi.Api.Controllers;
[ApiController][Authorize(Policy=AuthorizationPolicies.InventoryRead)]
[ProducesResponseType<ProblemDetails>(StatusCodes.Status400BadRequest,"application/problem+json",Description="The request failed validation.")]
[ProducesResponseType<ProblemDetails>(StatusCodes.Status401Unauthorized,"application/problem+json",Description="Authentication is required or the access token is invalid.")]
[ProducesResponseType<ProblemDetails>(StatusCodes.Status403Forbidden,"application/problem+json",Description="The authenticated user lacks the required permission.")]
[ProducesResponseType<ProblemDetails>(StatusCodes.Status500InternalServerError,"application/problem+json",Description="An unexpected server error occurred.")]
public sealed class LowStockController(ILowStockService service):ControllerBase
{
 [Authorize(Policy=AuthorizationPolicies.LowStockManage)][HttpPut("api/low-stock-thresholds/products/{productId:guid}/warehouses/{warehouseId:guid}/locations/{locationId:guid}")][EndpointSummary("Configure low-stock threshold")][EndpointDescription("Creates or updates the single threshold for an exact product, warehouse, and location position.")][ProducesResponseType<LowStockThresholdResponse>(StatusCodes.Status200OK,Description="Returns the configured threshold.")][ProducesResponseType<ProblemDetails>(StatusCodes.Status404NotFound,"application/problem+json",Description="The product, warehouse, or location was not found.")][ProducesResponseType<ProblemDetails>(StatusCodes.Status409Conflict,"application/problem+json",Description="The request conflicts with current resource state.")] public Task<LowStockThresholdResponse> Upsert(Guid productId,Guid warehouseId,Guid locationId,UpsertLowStockThresholdRequest request,CancellationToken ct)=>service.UpsertThresholdAsync(productId,warehouseId,locationId,request,ct);
 [HttpGet("api/low-stock-thresholds/products/{productId:guid}/warehouses/{warehouseId:guid}/locations/{locationId:guid}")][EndpointSummary("Get low-stock threshold")][EndpointDescription("Returns the configured threshold for an exact inventory position.")][ProducesResponseType<LowStockThresholdResponse>(StatusCodes.Status200OK,Description="Returns the requested threshold.")][ProducesResponseType<ProblemDetails>(StatusCodes.Status404NotFound,"application/problem+json",Description="The threshold was not found.")] public Task<LowStockThresholdResponse> Get(Guid productId,Guid warehouseId,Guid locationId,CancellationToken ct)=>service.GetThresholdAsync(productId,warehouseId,locationId,ct);
 [HttpGet("api/low-stock-thresholds")][EndpointSummary("List low-stock thresholds")][EndpointDescription("Returns filtered and paged low-stock threshold configuration.")][ProducesResponseType<PagedResult<LowStockThresholdResponse>>(StatusCodes.Status200OK,Description="Returns the requested threshold page.")] public Task<PagedResult<LowStockThresholdResponse>> Thresholds([FromQuery]LowStockThresholdQuery q,CancellationToken ct)=>service.ListThresholdsAsync(q,ct);
 [HttpGet("api/low-stock")][EndpointSummary("List low-stock positions")][EndpointDescription("Returns enabled positions where derived AvailableQuantity is at or below the threshold, treating a missing balance as zero.")][ProducesResponseType<PagedResult<LowStockResponse>>(StatusCodes.Status200OK,Description="Returns the requested low-stock position page.")] public Task<PagedResult<LowStockResponse>> Low([FromQuery]LowStockQuery q,CancellationToken ct)=>service.ListLowStockAsync(q,ct);
 [HttpGet("api/low-stock-alerts")][EndpointSummary("List low-stock alerts")][EndpointDescription("Returns paged persistent low-stock alert history, including active and resolved alerts.")][ProducesResponseType<PagedResult<LowStockAlertResponse>>(StatusCodes.Status200OK,Description="Returns the requested alert page.")] public Task<PagedResult<LowStockAlertResponse>> Alerts([FromQuery]LowStockAlertQuery q,CancellationToken ct)=>service.ListAlertsAsync(q,ct);
}
