using InventoryWarehouseApi.Application.Authentication;
using InventoryWarehouseApi.Application.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace InventoryWarehouseApi.Api.Controllers;
[ApiController][Route("api/users")][Authorize(Policy=AuthorizationPolicies.AdminOnly)]
[ProducesResponseType<ProblemDetails>(StatusCodes.Status400BadRequest,"application/problem+json",Description="The request failed validation.")]
[ProducesResponseType<ProblemDetails>(StatusCodes.Status401Unauthorized,"application/problem+json",Description="Authentication is required or the access token is invalid.")]
[ProducesResponseType<ProblemDetails>(StatusCodes.Status403Forbidden,"application/problem+json",Description="The authenticated user lacks Admin permission.")]
[ProducesResponseType<ProblemDetails>(StatusCodes.Status500InternalServerError,"application/problem+json",Description="An unexpected server error occurred.")]
public sealed class UsersController(IUserService service):ControllerBase
{
 [HttpPost][EndpointSummary("Create user")][EndpointDescription("Creates an application user with a hashed password and assigned role.")][ProducesResponseType<UserResponse>(StatusCodes.Status201Created,Description="Creates and returns the user.")][ProducesResponseType<ProblemDetails>(StatusCodes.Status409Conflict,"application/problem+json",Description="The email conflicts with an existing user.")]public async Task<ActionResult<UserResponse>>Create(CreateUserRequest request,CancellationToken ct){var u=await service.CreateAsync(request,ct);return CreatedAtAction(nameof(Get),new{id=u.Id},u);}
 [HttpGet][EndpointSummary("List users")][EndpointDescription("Returns a filtered and paged list of application users.")][ProducesResponseType<PagedResult<UserResponse>>(StatusCodes.Status200OK,Description="Returns the requested user page.")]public Task<PagedResult<UserResponse>>List([FromQuery]UserQuery q,CancellationToken ct)=>service.ListAsync(q,ct);
 [HttpGet("{id:guid}")][EndpointSummary("Get user")][EndpointDescription("Returns one application user by identifier.")][ProducesResponseType<UserResponse>(StatusCodes.Status200OK,Description="Returns the requested user.")][ProducesResponseType<ProblemDetails>(StatusCodes.Status404NotFound,"application/problem+json",Description="The user was not found.")]public Task<UserResponse>Get(Guid id,CancellationToken ct)=>service.GetAsync(id,ct);
 [HttpPut("{id:guid}/role")][EndpointSummary("Change user role")][EndpointDescription("Changes a user's role, revokes active refresh tokens, and preserves the last-active-Admin safeguard.")][ProducesResponseType<UserResponse>(StatusCodes.Status200OK,Description="Returns the updated user.")][ProducesResponseType<ProblemDetails>(StatusCodes.Status404NotFound,"application/problem+json",Description="The user was not found.")][ProducesResponseType<ProblemDetails>(StatusCodes.Status409Conflict,"application/problem+json",Description="The change would remove the last active Admin.")]public Task<UserResponse>Role(Guid id,UpdateUserRoleRequest request,CancellationToken ct)=>service.ChangeRoleAsync(id,request,ct);
 [HttpPut("{id:guid}/status")][EndpointSummary("Change user status")][EndpointDescription("Activates or deactivates a user, revokes refresh tokens on deactivation, and preserves the last-active-Admin safeguard.")][ProducesResponseType<UserResponse>(StatusCodes.Status200OK,Description="Returns the updated user.")][ProducesResponseType<ProblemDetails>(StatusCodes.Status404NotFound,"application/problem+json",Description="The user was not found.")][ProducesResponseType<ProblemDetails>(StatusCodes.Status409Conflict,"application/problem+json",Description="The change would deactivate the last active Admin.")]public Task<UserResponse>Status(Guid id,UpdateUserStatusRequest request,CancellationToken ct)=>service.ChangeStatusAsync(id,request,ct);
}
