// <auto-generated />
using System;
using InventoryWarehouseApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryWarehouseApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryWarehouseDbContext))]
    [Migration("20260824152328_AddInventoryReservations")]
    partial class AddInventoryReservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.InventoryAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AdjustedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AdjustedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("AdjustmentType")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("StockMovementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StockMovementId")
                        .IsUnique();

                    b.HasIndex("WarehouseId", "WarehouseLocationId");

                    b.HasIndex("ProductId", "WarehouseId", "WarehouseLocationId", "AdjustedAtUtc", "Id")
                        .IsDescending(false, false, false, true, true)
                        .HasDatabaseName("IX_InventoryAdjustments_Position_AdjustedAtUtc");

                    b.ToTable("InventoryAdjustments", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryAdjustments_AdjustmentType_Supported", "[AdjustmentType] IN (1, 2)");

                            t.HasCheckConstraint("CK_InventoryAdjustments_Quantity_Positive", "CAST([Quantity] AS decimal(18,3)) > 0");
                        });
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.InventoryBalance", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("OnHandQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("ReservedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("ProductId", "WarehouseId", "WarehouseLocationId");

                    b.HasIndex("ProductId", "WarehouseId");

                    b.HasIndex("WarehouseId", "WarehouseLocationId");

                    b.ToTable("InventoryBalances", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryBalances_OnHandQuantity_NonNegative", "CAST([OnHandQuantity] AS decimal(18,3)) >= 0");

                            t.HasCheckConstraint("CK_InventoryBalances_ReservedNotGreaterThanOnHand", "CAST([ReservedQuantity] AS decimal(18,3)) <= CAST([OnHandQuantity] AS decimal(18,3))");

                            t.HasCheckConstraint("CK_InventoryBalances_ReservedQuantity_NonNegative", "CAST([ReservedQuantity] AS decimal(18,3)) >= 0");
                        });
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.InventoryReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FulfilledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("FulfillmentMovementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FulfillmentMovementId")
                        .IsUnique()
                        .HasFilter("[FulfillmentMovementId] IS NOT NULL");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_InventoryReservations_CreatedAtUtc_Id");

                    b.HasIndex("ReferenceType", "ReferenceId");

                    b.HasIndex("WarehouseId", "WarehouseLocationId");

                    b.HasIndex("ProductId", "WarehouseId", "WarehouseLocationId", "CreatedAtUtc", "Id")
                        .IsDescending(false, false, false, true, true)
                        .HasDatabaseName("IX_InventoryReservations_Position_CreatedAtUtc_Id");

                    b.ToTable("InventoryReservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryReservations_LifecycleConsistency", "([Status] = 1 AND [ReleasedAtUtc] IS NULL AND [FulfilledAtUtc] IS NULL AND [FulfillmentMovementId] IS NULL) OR\n([Status] = 2 AND [ReleasedAtUtc] IS NOT NULL AND [ReleasedAtUtc] >= [CreatedAtUtc] AND [FulfilledAtUtc] IS NULL AND [FulfillmentMovementId] IS NULL) OR\n([Status] = 3 AND [ReleasedAtUtc] IS NULL AND [FulfilledAtUtc] IS NOT NULL AND [FulfilledAtUtc] >= [CreatedAtUtc] AND [FulfillmentMovementId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_InventoryReservations_Quantity_Positive", "CAST([Quantity] AS decimal(18,3)) > 0");

                            t.HasCheckConstraint("CK_InventoryReservations_ReferencePair", "([ReferenceType] IS NULL AND [ReferenceId] IS NULL) OR ([ReferenceType] IS NOT NULL AND [ReferenceId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_InventoryReservations_Status_Supported", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Sku");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "WarehouseLocationId");

                    b.HasIndex("ProductId", "WarehouseId", "WarehouseLocationId", "OccurredAtUtc", "Id")
                        .IsDescending(false, false, false, true, true)
                        .HasDatabaseName("IX_StockMovements_Position_OccurredAtUtc");

                    b.ToTable("StockMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockMovements_MovementType_Supported", "[MovementType] IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_StockMovements_Quantity_Positive", "CAST([Quantity] AS decimal(18,3)) > 0");
                        });
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Warehouses_Code");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.WarehouseLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_WarehouseLocations_WarehouseId_Code");

                    b.ToTable("WarehouseLocations", (string)null);
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.WarehouseTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DestinationWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationWarehouseLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceWarehouseLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_WarehouseTransfers_CreatedAtUtc_Id");

                    b.HasIndex("DestinationWarehouseId", "DestinationWarehouseLocationId");

                    b.HasIndex("SourceWarehouseId", "SourceWarehouseLocationId");

                    b.ToTable("WarehouseTransfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_WarehouseTransfers_DifferentPositions", "[SourceWarehouseId] <> [DestinationWarehouseId] OR [SourceWarehouseLocationId] <> [DestinationWarehouseLocationId]");

                            t.HasCheckConstraint("CK_WarehouseTransfers_Status_Supported", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.WarehouseTransferItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid?>("TransferInMovementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransferOutMovementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseTransferId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransferInMovementId")
                        .IsUnique()
                        .HasDatabaseName("UX_WarehouseTransferItems_TransferInMovementId")
                        .HasFilter("[TransferInMovementId] IS NOT NULL");

                    b.HasIndex("TransferOutMovementId")
                        .IsUnique()
                        .HasDatabaseName("UX_WarehouseTransferItems_TransferOutMovementId")
                        .HasFilter("[TransferOutMovementId] IS NOT NULL");

                    b.HasIndex("WarehouseTransferId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_WarehouseTransferItems_Transfer_Product");

                    b.ToTable("WarehouseTransferItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_WarehouseTransferItems_MovementPair", "([TransferOutMovementId] IS NULL AND [TransferInMovementId] IS NULL) OR ([TransferOutMovementId] IS NOT NULL AND [TransferInMovementId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_WarehouseTransferItems_Quantity_Positive", "CAST([Quantity] AS decimal(18,3)) > 0");
                        });
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.InventoryAdjustment", b =>
                {
                    b.HasOne("InventoryWarehouseApi.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.StockMovement", null)
                        .WithOne()
                        .HasForeignKey("InventoryWarehouseApi.Domain.Entities.InventoryAdjustment", "StockMovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.WarehouseLocation", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId", "WarehouseLocationId")
                        .HasPrincipalKey("WarehouseId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.InventoryBalance", b =>
                {
                    b.HasOne("InventoryWarehouseApi.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.WarehouseLocation", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId", "WarehouseLocationId")
                        .HasPrincipalKey("WarehouseId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.InventoryReservation", b =>
                {
                    b.HasOne("InventoryWarehouseApi.Domain.Entities.StockMovement", null)
                        .WithMany()
                        .HasForeignKey("FulfillmentMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.WarehouseLocation", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId", "WarehouseLocationId")
                        .HasPrincipalKey("WarehouseId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("InventoryWarehouseApi.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.WarehouseLocation", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId", "WarehouseLocationId")
                        .HasPrincipalKey("WarehouseId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.WarehouseLocation", b =>
                {
                    b.HasOne("InventoryWarehouseApi.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.WarehouseTransfer", b =>
                {
                    b.HasOne("InventoryWarehouseApi.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("DestinationWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("SourceWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.WarehouseLocation", null)
                        .WithMany()
                        .HasForeignKey("DestinationWarehouseId", "DestinationWarehouseLocationId")
                        .HasPrincipalKey("WarehouseId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.WarehouseLocation", null)
                        .WithMany()
                        .HasForeignKey("SourceWarehouseId", "SourceWarehouseLocationId")
                        .HasPrincipalKey("WarehouseId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.WarehouseTransferItem", b =>
                {
                    b.HasOne("InventoryWarehouseApi.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.StockMovement", null)
                        .WithMany()
                        .HasForeignKey("TransferInMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.StockMovement", null)
                        .WithMany()
                        .HasForeignKey("TransferOutMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InventoryWarehouseApi.Domain.Entities.WarehouseTransfer", null)
                        .WithMany("Items")
                        .HasForeignKey("WarehouseTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryWarehouseApi.Domain.Entities.WarehouseTransfer", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
