using System.Net;using System.Net.Http.Json;using InventoryWarehouseApi.Application.Common;using InventoryWarehouseApi.Application.LowStock;using InventoryWarehouseApi.Application.Products;using InventoryWarehouseApi.Application.Warehouses;using InventoryWarehouseApi.Application.WarehouseLocations;using InventoryWarehouseApi.Infrastructure.Persistence;using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.DependencyInjection;
namespace InventoryWarehouseApi.IntegrationTests;
public sealed class Phase08ApiTests
{
 [Fact] public async Task Threshold_UpsertWithoutBalance_AndLowStockQueryWork(){using ApiFactory f=new();using var c=f.CreateClient();var p=await Position(c,"zero");string url=$"/api/low-stock-thresholds/products/{p.P}/warehouses/{p.W}/locations/{p.L}";var first=await (await c.PutAsJsonAsync(url,new UpsertLowStockThresholdRequest(0,true))).Content.ReadFromJsonAsync<LowStockThresholdResponse>();Assert.NotNull(first);var second=await (await c.PutAsJsonAsync(url,new UpsertLowStockThresholdRequest(5,true))).Content.ReadFromJsonAsync<LowStockThresholdResponse>();Assert.Equal(first!.Id,second!.Id);Assert.Equal(first.CreatedAtUtc,second.CreatedAtUtc);Assert.Equal(second.Id,(await c.GetFromJsonAsync<LowStockThresholdResponse>(url))!.Id);var low=await c.GetFromJsonAsync<PagedResult<LowStockResponse>>("/api/low-stock");Assert.Single(low!.Items);Assert.Equal((0m,0m,0m),(low.Items[0].OnHandQuantity,low.Items[0].ReservedQuantity,low.Items[0].AvailableQuantity));}
 [Theory][InlineData(-1)][InlineData(1.0001)] public async Task Threshold_InvalidQuantityIsBadRequest(decimal q){using ApiFactory f=new();using var c=f.CreateClient();var p=await Position(c,Guid.NewGuid().ToString("N"));Assert.Equal(HttpStatusCode.BadRequest,(await c.PutAsJsonAsync($"/api/low-stock-thresholds/products/{p.P}/warehouses/{p.W}/locations/{p.L}",new UpsertLowStockThresholdRequest(q,true))).StatusCode);}
 [Fact] public async Task Monitoring_IsIdempotentAndResolvesAfterDisable(){using ApiFactory f=new();using var c=f.CreateClient();var p=await Position(c,"monitor");await c.PutAsJsonAsync($"/api/low-stock-thresholds/products/{p.P}/warehouses/{p.W}/locations/{p.L}",new UpsertLowStockThresholdRequest(1,true));using(var s=f.Services.CreateScope()){var monitor=s.ServiceProvider.GetRequiredService<ILowStockMonitoringService>();Assert.Equal(1,(await monitor.RunAsync(DateTimeOffset.UtcNow,CancellationToken.None)).TriggeredAlertCount);Assert.Equal(0,(await monitor.RunAsync(DateTimeOffset.UtcNow.AddSeconds(1),CancellationToken.None)).TriggeredAlertCount);}await c.PutAsJsonAsync($"/api/low-stock-thresholds/products/{p.P}/warehouses/{p.W}/locations/{p.L}",new UpsertLowStockThresholdRequest(1,false));using(var s=f.Services.CreateScope()){var monitor=s.ServiceProvider.GetRequiredService<ILowStockMonitoringService>();Assert.Equal(1,(await monitor.RunAsync(DateTimeOffset.UtcNow.AddSeconds(2),CancellationToken.None)).ResolvedAlertCount);var db=s.ServiceProvider.GetRequiredService<InventoryWarehouseDbContext>();Assert.Single(await db.LowStockAlerts.Where(x=>x.ResolvedAtUtc!=null).ToListAsync());}}
 private static async Task<(Guid P,Guid W,Guid L)> Position(HttpClient c,string s){var p=(await (await c.PostAsJsonAsync("/api/products",new CreateProductRequest("sku-"+s,s,null))).Content.ReadFromJsonAsync<ProductResponse>())!;var w=(await (await c.PostAsJsonAsync("/api/warehouses",new CreateWarehouseRequest("wh-"+s,s,null))).Content.ReadFromJsonAsync<WarehouseResponse>())!;var l=(await (await c.PostAsJsonAsync($"/api/warehouses/{w.Id}/locations",new CreateWarehouseLocationRequest("l-"+s,s,null))).Content.ReadFromJsonAsync<WarehouseLocationResponse>())!;return(p.Id,w.Id,l.Id);}
}
