using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.IdentityModel.Tokens.Jwt;
using InventoryWarehouseApi.Application.Authentication;
using InventoryWarehouseApi.Domain.Entities;
using InventoryWarehouseApi.Domain.Enums;
using InventoryWarehouseApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using InventoryWarehouseApi.Application.Products;
using InventoryWarehouseApi.Application.Warehouses;
using InventoryWarehouseApi.Application.WarehouseLocations;
using InventoryWarehouseApi.Application.Inventory;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore.Metadata;
namespace InventoryWarehouseApi.IntegrationTests;
public sealed class Phase09AuthenticationTests
{
 [Fact]public async Task RealAuthentication_AnonymousSurfaceIsNarrowAndIntentional()
 {using var f=new ApiFactory(true);using var c=f.CreateClient();Assert.Equal(HttpStatusCode.OK,(await c.GetAsync("/openapi/v1.json")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.GetAsync("/scalar/v1")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.GetAsync("/health")).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/login",new LoginRequest("missing@inventory.local","WrongPassword1!"))).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.GetAsync("/api/products")).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.GetAsync("/api/auth/me")).StatusCode);}
 [Fact]public async Task Login_RealJwt_ProtectsEndpointsAndHasExpectedClaims()
 {using var f=new ApiFactory(true);await Seed(f,"manager@inventory.local",UserRole.InventoryManager);using var anonymous=f.CreateClient();Assert.Equal(HttpStatusCode.Unauthorized,(await anonymous.GetAsync("/api/products")).StatusCode);var auth=await Login(anonymous,"manager@inventory.local");Assert.False(string.IsNullOrWhiteSpace(auth.AccessToken));Assert.False(string.IsNullOrWhiteSpace(auth.RefreshToken));var jwt=new JwtSecurityTokenHandler().ReadJwtToken(auth.AccessToken);Assert.Contains(jwt.Claims,x=>x.Type==JwtRegisteredClaimNames.Sub);Assert.Contains(jwt.Claims,x=>x.Type==System.Security.Claims.ClaimTypes.Role&&x.Value=="InventoryManager");Assert.Equal(6,jwt.Claims.Count(x=>x.Type==Permissions.ClaimType));anonymous.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",auth.AccessToken);Assert.Equal(HttpStatusCode.OK,(await anonymous.GetAsync("/api/auth/me")).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await anonymous.GetAsync("/api/users")).StatusCode);}
 [Fact]public async Task LoginFailures_AreGeneric()
 {using var f=new ApiFactory(true);await Seed(f,"active@inventory.local",UserRole.Viewer);using var c=f.CreateClient();var unknown=await c.PostAsJsonAsync("/api/auth/login",new LoginRequest("missing@inventory.local","WrongPassword1!"));var wrong=await c.PostAsJsonAsync("/api/auth/login",new LoginRequest("active@inventory.local","WrongPassword1!"));Assert.Equal(HttpStatusCode.Unauthorized,unknown.StatusCode);var u=await unknown.Content.ReadFromJsonAsync<System.Text.Json.JsonElement>();var w=await wrong.Content.ReadFromJsonAsync<System.Text.Json.JsonElement>();Assert.Equal("Invalid email or password.",u.GetProperty("detail").GetString());Assert.Equal(u.GetProperty("detail").GetString(),w.GetProperty("detail").GetString());}
 [Fact]public async Task RefreshRotatesAndLogoutIsIdempotent_RawTokenIsNeverStored()
 {using var f=new ApiFactory(true);await Seed(f,"viewer@inventory.local",UserRole.Viewer);using var c=f.CreateClient();var a=await Login(c,"viewer@inventory.local");var rotated=await (await c.PostAsJsonAsync("/api/auth/refresh",new RefreshTokenRequest(a.RefreshToken))).Content.ReadFromJsonAsync<AuthTokenResponse>();Assert.NotNull(rotated);Assert.NotEqual(a.RefreshToken,rotated.RefreshToken);Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/refresh",new RefreshTokenRequest(a.RefreshToken))).StatusCode);using(var scope=f.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<InventoryWarehouseDbContext>();Assert.DoesNotContain(await db.RefreshTokens.Select(x=>x.TokenHash).ToListAsync(),x=>x==a.RefreshToken||x==rotated.RefreshToken);}Assert.Equal(HttpStatusCode.NoContent,(await c.PostAsJsonAsync("/api/auth/logout",new LogoutRequest(rotated.RefreshToken))).StatusCode);Assert.Equal(HttpStatusCode.NoContent,(await c.PostAsJsonAsync("/api/auth/logout",new LogoutRequest(rotated.RefreshToken))).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/refresh",new RefreshTokenRequest(rotated.RefreshToken))).StatusCode);}
 [Fact]public async Task InvalidJwt_ReturnsUnauthorized(){using var f=new ApiFactory(true);using var c=f.CreateClient();c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer","malformed.token.value");Assert.Equal(HttpStatusCode.Unauthorized,(await c.GetAsync("/api/products")).StatusCode);}
 [Fact]public async Task AdjustmentAlwaysUsesAuthenticatedCanonicalEmail()
 {using var f=new ApiFactory(true);await Seed(f,"manager@inventory.local",UserRole.InventoryManager);using var c=f.CreateClient();var auth=await Login(c,"manager@inventory.local");c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",auth.AccessToken);var product=await Read<ProductResponse>(await c.PostAsJsonAsync("/api/products",new CreateProductRequest("AUTH-SKU","Auth product",null)));var warehouse=await Read<WarehouseResponse>(await c.PostAsJsonAsync("/api/warehouses",new CreateWarehouseRequest("AUTH-WH","Auth warehouse",null)));var location=await Read<WarehouseLocationResponse>(await c.PostAsJsonAsync($"/api/warehouses/{warehouse.Id}/locations",new CreateWarehouseLocationRequest("AUTH-L","Auth location",null)));var response=await c.PostAsJsonAsync($"/api/inventory/products/{product.Id}/warehouses/{warehouse.Id}/locations/{location.Id}/adjustments/increase",new{quantity=1,reason="Authenticated cycle count",adjustedBy="spoofed@example.com"});var adjustment=await Read<InventoryAdjustmentOperationResponse>(response);Assert.Equal("manager@inventory.local",adjustment.AdjustedBy);using var scope=f.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<InventoryWarehouseDbContext>();Assert.Equal("manager@inventory.local",(await db.InventoryAdjustments.SingleAsync()).AdjustedBy);}
 [Fact]public async Task RefreshTokenForeignKey_RestrictsUserDeletionAndPreservesHistory()
 {using var f=new ApiFactory(true);await Seed(f,"history@inventory.local",UserRole.Viewer);using var c=f.CreateClient();await Login(c,"history@inventory.local");using var scope=f.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<InventoryWarehouseDbContext>();var foreignKey=db.Model.FindEntityType(typeof(RefreshToken))!.GetForeignKeys().Single(x=>x.PrincipalEntityType.ClrType==typeof(User));Assert.Equal(DeleteBehavior.Restrict,foreignKey.DeleteBehavior);Guid userId=await db.Users.Where(x=>x.Email=="history@inventory.local").Select(x=>x.Id).SingleAsync();Assert.Equal(1,await db.RefreshTokens.CountAsync(x=>x.UserId==userId));await Assert.ThrowsAsync<SqliteException>(()=>db.Database.ExecuteSqlInterpolatedAsync($"DELETE FROM Users WHERE Id = {userId}"));Assert.Equal(1,await db.RefreshTokens.CountAsync(x=>x.UserId==userId));}
 private static async Task<AuthTokenResponse>Login(HttpClient c,string email){var response=await c.PostAsJsonAsync("/api/auth/login",new LoginRequest(email,"StrongPassword1!"));response.EnsureSuccessStatusCode();return(await response.Content.ReadFromJsonAsync<AuthTokenResponse>())!;}
 private static async Task<T>Read<T>(HttpResponseMessage response){response.EnsureSuccessStatusCode();return(await response.Content.ReadFromJsonAsync<T>())!;}
 private static async Task Seed(ApiFactory f,string email,UserRole role){using var scope=f.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<InventoryWarehouseDbContext>();var hashing=scope.ServiceProvider.GetRequiredService<IPasswordHashService>();var now=DateTimeOffset.UtcNow;var draft=new User(Guid.NewGuid(),email,"Test User","pending",role,now);var user=new User(draft.Id,email,"Test User",hashing.HashPassword(draft,"StrongPassword1!"),role,now);db.Users.Add(user);await db.SaveChangesAsync();}
}
