<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.11" />
    <ProjectReference Include="..\InventoryWarehouseApi.Application\InventoryWarehouseApi.Application.csproj" />
    <ProjectReference Include="..\InventoryWarehouseApi.Domain\InventoryWarehouseApi.Domain.csproj" />
  </ItemGroup>

</Project>
